### PR TITLE
feat: migrate from Openai sdk to Azure OpenAI SDK

### PR DESCRIPTION
**Pull request by glaucia86**
This PR is related with #22 

**WORK IN PROGRESS**

p.s.: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/openai/openai/samples/v1-beta/typescript

### CODE REVIEW

**Comment by glaucia86** [comment]
@anfibiacreativa and @sinedied there's a mistake here.... the bot closed this PR here... what happened with this issue?

**Comment by sinedied** [comment]
It seems you removed your GitHub repo, that's what triggered the closing

**Comment by glaucia86** [comment]
> It seems you removed your GitHub repo, that's what triggered the closing

Hi, @sinedied!
But I didn't remove it... it was the robot that removed it (and what a strange robot... it even included me as the one who closed the PR).
What should I do? Should I continue or not? If not, I'll focus on doing something else for our team.

p.s.: The PR was under the forked project was private under the @anfibiacreativa handle

image

**Comment by glaucia86** [comment]
Just to clarify the information above

Captura de Tela 2023-09-21 às 19 32 07

**Comment by sinedied** [comment]
Yes, it seems that when we moved the repo it closed automatically the PR.
Anyway that's not an issue, as your work is not lost and it's easily recoverable if you update the remote on your side.
For now let's wait a bit as we need more clarification whether this migration should be continued or not

**Pull request closed without merging**
