### PR TITLE
Pass the selected approach to the chat component and to the api call

### PR DESCRIPTION
**Pull request by JasonHaley**
### This issue is for a: (mark with an `x`)

```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

> azd auth login
> azd up

> go to static web app
> select any of the default search questions and click the search buttoon
> open the though process
> verify there is text like "[DynamicTool]" in there
> Open the Developer Settings in upper right corner
> Notice the "Retrieve-Then-Read" is selected

The ask-read-retrieve-read is the approach that uses the Dynamic Tool. 

You can try changing the approach in the Developer Settings, but it does not seem to work.

Also the OneShot.tsx file does have the rrr hard-coded.

### Expected/desired behavior

> Change the approach being used when the Developer Setting is changed

### CODE REVIEW

**Comment by JasonHaley** [comment]
@microsoft-github-policy-service agree

**Review by sinedied — APPROVED** [review]
Thanks for the fix!

**Comment by sinedied** [comment]
It seems the Playwright tests are failing, could you check that it works for you? It may need an update with your fix.

```sh
# once
npm run install:playwright

npm run test:playwright
```

**Comment by JasonHaley** [comment]
I'll take a look at it this afternoon and let you know.

**Comment by JasonHaley** [comment]
@sinedied I'm not sure how to get the change into the branch. I tried putting it in my fork and this repo, but neither show up on this pr.

I think the problem is line 25 in OneShot.tsx needs to be:

`const [approach, setApproach] = useState<Approaches>(Approaches.ReadRetrieveRead);`

I ran the tests and that seems to fix most of them, but there are still 2 unrelated ones failing on my machine, which I'm guessin is some configuration on my system.

**Comment by sinedied** [comment]
Thanks, that's perfect :)

**Pull request merged**
